package com.bank.BankApplication.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TransactionDTO {

    @Schema(
            description = "Type of transaction, e.g., CREDIT or DEBIT",
            example = "CREDIT"
    )
    private String transactionType;

    @Schema(
            description = "Amount involved in the transaction",
            example = "1500.00"
    )
    private BigDecimal amount;

    @Schema(
            description = "Account number associated with the transaction",
            example = "1234567890"
    )
    private String accountNumber;

    @Schema(
            description = "Status of the transaction, e.g., SUCCESS or FAILED",
            example = "SUCCESS"
    )
    private String status;

    @Schema(
            description = "Transaction ID generated by the system",
            example = "2c9d1af1-0a12-4e79-a3cc-6b5f5d1f44b7",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private String transactionId;

    @Schema(
            description = "Date and time when the transaction occurred",
            example = "2025-04-15T10:30:00",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private LocalDateTime transactionDateandTime;
}
